# ArgoCD Application for MyBank Frontend
# This configures ArgoCD to automatically deploy and sync the frontend chart

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mybank-frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    tier: frontend
    environment: development
spec:
  project: default

  source:
    repoURL: https://github.com/your-org/mybank.git
    targetRevision: HEAD
    path: helm/frontend

    helm:
      releaseName: mybank-frontend
      valueFiles:
        - values.yaml
      values: |
        global:
          namespace: mybank
          imagePullPolicy: IfNotPresent
        frontend:
          enabled: true
          replicas: 2
          env:
            NODE_ENV: development
            NEXT_PUBLIC_API_URL: "https://api.mybank.com"

  destination:
    server: https://kubernetes.default.svc
    namespace: mybank

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false

    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  info:
    - name: 'Depends on'
      value: 'mybank-services'

  revisionHistoryLimit: 10
